networks:
  default:
    name: undersigned-network

services:

  data-collector:
    image: data-collector
    build: ./data-collector
    container_name: data-collector
    env_file: .env
    volumes:
      - ./secrets:/secrets
      - ./data-collector/src:/app/src
      - ./data:/app/data

  data-processor:
    image: data-processor
    build: ./data-processor
    container_name: data-processor
    env_file: .env
    volumes:
      - ./secrets:/secrets
      - ./data-processor/src:/app/src
      - ./data:/app/data
    depends_on:
      data-collector:
        condition: service_completed_successfully

  campaign-builder:
    image: campaign-builder
    build: ./campaign-builder
    container_name: campaign-builder
    env_file: .env
    volumes:
      - ./secrets:/secrets
      - ./campaign-builder/src:/app/src
      - ./data:/app/data
    depends_on:
      data-processor:
        condition: service_completed_successfully

  rule-passages:
    image: rule-passages
    build: ./rule-passages
    container_name: rule-passages
    env_file: .env
    volumes:
      - ./secrets:/secrets
      - ./rule-passages/src:/app/src
    environment:
      CHROMA_HOST: chromadb
      CHROMA_PORT: 8000
    depends_on:
      chromadb:
        condition: service_started

  api-service:
    image: api-service
    build: ./api-service
    container_name: api-service
    env_file: .env
    volumes:
      - ./secrets:/secrets
      - ./api-service/src:/app/src
    ports:
      - 8000:8000
    environment:
      CHROMA_HOST: chromadb
      CHROMA_PORT: 8000
    depends_on:
      chromadb:
        condition: service_started
      campaign-builder:
        condition: service_completed_successfully
      rule-passages:
        condition: service_completed_successfully

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:80
    depends_on:
      api-service:
        condition: service_started

  chromadb:
    image: chromadb/chroma:1.5.9
    container_name: undersigned-chromadb
    ports:
      - 9000:8000
    volumes:
      - ./docker-volumes/chromadb:/data
